# Configuración básica para Jekyll
title: "¿QUÉ HAY DETRÁS DEL PASAJE?"
description: "Un día como conductor de microbuses en CDMX."
baseurl: "/que.hay.detras.del.pasaje"
url: "https://jannetmann.github.io"

# Configuración básica de Jekyll
markdown: kramdown
highlighter: rouge
